ALTER TABLE Student
MODIFY COLUMN birthday DATE NOT NULL;

ALTER TABLE Mark
MODIFY COLUMN subject_id BIGINT NOT NULL,
MODIFY COLUMN student_id BIGINT NOT NULL,
ADD CONSTRAINT markCheck CHECK (mark >= 1 AND mark <= 10);

ALTER TABLE Subject
ADD CONSTRAINT gradeCheck CHECK (grade >= 1 AND grade <= 10);

ALTER TABLE PaymentType
MODIFY COLUMN name VARCHAR(100) UNIQUE;

ALTER TABLE Payment
MODIFY COLUMN amount DECIMAL NOT NULL,
MODIFY COLUMN type_id BIGINT NOT NULL,
MODIFY COLUMN payment_date DATETIME NOT NULL;