CREATE TABLE Student(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(250), birthday DATE, group INT);
CREATE TABLE Subject(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(250), description VARCHAR(250), grade INT);
CREATE TABLE PaymentType( id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(250));
CREATE TABLE Payment(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, amount DECIMAL, payment_date DATETIME, type_id BIGINT, student_id BIGINT, FOREIGN KEY(type_id) REFERENCES PaymentType(id), FOREIGN KEY(student_id) REFERENCES Student(id));
CREATE TABLE Mark(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, mark INT, subject_id BIGINT, student_id BIGINT, FOREIGN KEY(subject_id) REFERENCES Subject(id), FOREIGN KEY(student_id) REFERENCES Student(id));

